sudo: required
language: python
python:
    - 2.7
    - 3.5
    - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
before_install:
    - sudo apt-get install python-dev gfortran
install:
    - pip install -r requirements.txt
    - python setup.py install
script:
    - cd
    - python -m ffnet._tests
before_deploy:
    - cd $TRAVIS_BUILD_DIR
deploy:
    provider: pypi
    user: mwojc
    password:
        secure: Zxc+tq+rmhd3FiAMnUn8bDsOCbfq8K+BJZ6FOyiit7uYtFyRe+M0AC5DdBDQXfgj2yIB3LlCvTmFv/ef1+RlQc+C2760EEJQwY1E/oB1EXQFAhXfM+RYvTp2HPzVXVgOJXJhO2PHkst0MnCNezSuLZ1zj2fPIn8ZmHpSDvGwZ8L1rQ5mWPjstIpV6FKvPYDYAnruWkA0DEYRRf+oXBT2uPvU8a8WPSnwa/KMPn4vka5jlS+oZ/BPXPa4vjm1Z9Yfo3zk8qEqfZM2+ybPfqJzcvOd0ugprXAd2yEaOCNdul2aewPZ2+nsDPi1r4+AmEvUZKlx+1t9hLfZypsdBY8sUu/AhWeeAMV+QBIb9SuuVGgHBnnl36XbjXZJwsyDYWQzE7S/OZA9iXfQvp5NahHYfzC0LP7gbWHLCXTeT0V50c7VVaPRsJy+mesB80CFRXEi0gYbFjm5IzNZoQ9gsfk9CO2+C3WwKvBXnGIjFAhG5qPWi38zuhAEb4NYGRowrnxkfbjM1a16o0NhCCo8mjGx/vCX0B9aG8rK7VcnWh2MS1W7mtKcDLzwifo6+qGl6X9rSrwho274b8vJy4QnslIJrOzkipEbi2gtjcV+3kZ7HQDrWH23iM7c9gdl++QQLlJbXznzC58acTiBr4jBHrThsNnuyPUL/KoGHPKRQ7PEs1M=
    skip_cleanup: true
    on:
        tags: true
        branch: master
