sudo: required
language: python
python:
    - 2.7
    - 3.6
before_install:
    - sudo apt-get install python-dev gfortran
    - sudo pip install -r requirements.txt
install:
    - python setup.py install
script:
    - python -m ffnet._tests

#deploy:
  #provider: pypi
  #user: mwojc
  #password:
    #secure: my_secure_password
  #on:
    #tags: true
    #branch: master
